# Generated by Django 5.0.6 on 2024-08-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='account',
        ),
    ]
