# Generated by Django 5.0.6 on 2024-07-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_orderitem_product_variant'),
        ('products', '0007_product_max_purchase_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_product', to='products.product'),
        ),
    ]
