# Generated by Django 5.0.6 on 2024-07-21 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderitem_options_and_more'),
        ('users', '0003_alter_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_orders', to='users.account'),
        ),
    ]
