# Generated by Django 5.0.6 on 2024-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_coupon_discount_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='delivery_date',
            new_name='completed_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash On Delivery'), ('paypal', 'PayPal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('deleted', 'Order Deleted'), ('placed', 'Order Placed'), ('completed', 'Delivery Completed'), ('cancelled', 'Order Cancelled')], default='cart', max_length=50),
        ),
    ]
