# Generated by Django 5.0.6 on 2024-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_delivery_date_orderitem_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
