# Generated by Django 5.0.6 on 2024-07-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('cart', 'Cart'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='cart', max_length=50, null=True),
        ),
    ]
