# Generated by Django 5.0.6 on 2024-07-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.PositiveIntegerField(default=100)),
                ('minimum_amount', models.PositiveIntegerField(default=500)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('deleted', 'Order Deleted'), ('placed', 'Order Placed'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled')], default='cart', max_length=50),
        ),
    ]
