# Generated by Django 5.0.6 on 2024-07-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='amount', max_length=50),
            preserve_default=False,
        ),
    ]
