# Generated by Django 5.0.6 on 2024-07-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_coupon_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash On Delivery'), ('paypal', 'PayPal'), ('razorpay', 'RazorPay')], max_length=50, null=True),
        ),
    ]
