# Generated by Django 5.0.6 on 2024-07-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_order_transaction_id_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_identifier',
        ),
    ]
