# Generated by Django 5.0.6 on 2024-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_coupon_options_coupon_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['is_expired', '-created_at']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('cart', 'Cart'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_request', 'Requested for Return'), ('returned', 'Returned')], default='cart', max_length=50, null=True),
        ),
    ]
