# Generated by Django 5.0.6 on 2024-08-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_coupon_options_orderitem_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon_discount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_deduction',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_charge_deduction',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('cancelled', 'Cancelled'), ('wallet', 'Added to Wallet')], default='pending', max_length=50, null=True),
        ),
    ]
