# Generated by Django 5.0.6 on 2024-08-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_orderitem_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='coupon_discount_deduction',
            new_name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_charge_deduction',
        ),
    ]
