# Generated by Django 5.0.6 on 2024-08-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_rename_coupon_discount_deduction_orderitem_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='coupon_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
