# Generated by Django 5.0.6 on 2024-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_orderitem_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash On Delivery'), ('paypal', 'PayPal'), ('razorpay', 'RazorPay'), ('wallet', 'Wallet')], max_length=50, null=True),
        ),
    ]
