# Generated by Django 5.0.6 on 2024-08-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('deleted', 'Order Deleted'), ('placed', 'Order Placed'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled'), ('pending', 'Pending')], default='cart', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('cart', 'Cart'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_request', 'Requested for Return'), ('returned', 'Returned'), ('pending', 'Pending')], default='cart', max_length=50, null=True),
        ),
    ]
