# Generated by Django 5.0.6 on 2024-07-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_purchase_qty',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
