# Generated by Django 5.0.6 on 2024-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_max_purchase_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders_recieved',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
