# Generated by Django 5.0.6 on 2024-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_orders_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='module_offer',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
