# Generated by Django 5.0.6 on 2024-08-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orders_recieved',
        ),
    ]
