# Generated by Django 5.0.6 on 2024-08-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stage',
            field=models.CharField(choices=[('stage1', 'Stage1'), ('stage2', 'Stage2'), ('stage3', 'Stage3')], default='stage3', max_length=50),
            preserve_default=False,
        ),
    ]
